#!/bin/sh

if [ -d "CMSSpark" ]; then
  echo "CMSSpark was already cloned"
else
  git clone https://github.com/vkuznet/CMSSpark
fi

if [ -d "CERNTasks.wiki" ]; then
  echo "CERNTasks.wiki was already cloned"
else
  git clone https://github.com/andrius-k/CERNTasks.wiki
fi