#!/bin/sh

# Parse date argument
date=20170228

if [[ -n $1 ]]
then
    date=$1
fi

date_length=${#date}
if [[ $date_length != 8 ]]
then
    echo 'Invalid date. Example: 20170228'
    exit
fi

echo 'Aggregating for date: '$date

# Chnage username in location value 
location=/cms/users/$USER/campaign_tier
hdir=hdfs://$location

# Copy script file that will be ran
cp aggregate_campaign_tier.py ../CMSSpark/src/python/CMSSpark/aggregate_campaign_tier.py

# Remove previous data first
hadoop fs -rm -r $location

PYTHONPATH=$(pwd)/../CMSSpark/src/python ../CMSSpark/bin/run_spark aggregate_campaign_tier.py --fout=$hdir --yarn --verbose --date=$date

hadoop fs -get $hdir .

# extract header
head -1 campaign_tier/part-00000 > campaign_tier_df.csv

# concatenate all parts except header
header=`cat campaign_tier_df.csv`
cat campaign_tier/part* | grep -v $header >> campaign_tier_df.csv
